# Project Euler Problem 2
#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
#
#           1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

function fib(n)
    back2 = 0
    back1 = 1
    next = 0

    if n == 0
        return 0
    end

    for i in 2:n-1
        next = back2 + back1
        back2 = back1
        back1 = next
    end

    return back1+back2
end


result = 0

i = 1
while true
    curr = fib(i)

    if curr > 4_000_000
        break
    end

    if curr % 2 == 0
        result += curr
    end

    i += 1
end

println(result)

