# Project Euler Problem 44
#
# Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
#
# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
#
# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
#
# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are
# pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

inv_pen(p) = (1+sqrt(24p+1))/6

function main()
    j = 3
    pj = 12
    while true
        i = 1
        pi = 1
        while i < j
            t = inv_pen(pj+pi)
            if t == round(Int64, t)
                s = inv_pen(pj-pi)
                if s == round(Int64, s)
                    return pj - pi
                end
            end
            pi += (3i+1)
            i+=1
        end
        pj += (3j+1)
        j += 1
    end
end

@time println(main())
