# Project Euler Problem 45
#
# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
#
# Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
# Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.
#
# Find the next triangle number that is also pentagonal and hexagonal.

function main()
    i = 1
    ti = big(1)

    j = 1
    pj = 1

    k = 1
    hk = 1

    while !(ti == pj == hk) || i==1 || i==285

        if ti <= pj && ti <= hk
            i += 1
            ti = div(i*(i+1), 2)

        elseif pj <= ti && pj <= hk
            j += 1
            pj = div(j*(3j-1), 2)

        else
            k += 1
            hk = k*(2k-1)
        end
    end

    println(ti)
end


main()
