# Project Euler Problem 45
#
# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
#
# Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
# Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.
#
# Find the next triangle number that is also pentagonal and hexagonal.

function main()
    # Every hexagonal number is also a triangle number.
    # Hence we only need H == P.

    # Pentagonal Numbers
    m = 1
    Pm = 1

    # Hexagonal Numbers
    n = 1
    Hn = 1

    # Skip the trivial case and the nontrivial case thats given.
    while !(Hn == Pm) || n==1 || n == 143
        if Hn <= Pm
            n += 1
            Hn = n*(2n-1)

        else
            m += 1
            Pm = div(m*(3m-1), 2)
        end
    end
    println(Hn)
end

main()

